name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /root/dezsanyilvantarto
          
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          mkdir -p /root/dezsanyilvantarto_backups
          
          docker compose cp backend:/src/instance/app.db /root/dezsanyilvantarto_backups/app_${TIMESTAMP}.db 2>/dev/null || echo "No existing container to backup from"
          
          git pull origin main
          
          docker compose down
          docker compose build
          docker compose up -d
          
          echo "Deployment completed at $(date)"
